"""Advanced SubStation Alpha (ASS) subtitle generation."""

from __future__ import annotations

from pathlib import Path

from video_mcp.errors import SubtitleGenerationFailed
from video_mcp.models import SubtitleSegment, Transcript
from video_mcp.subtitles.styles import ASSStyle, get_style_preset

PathLike = str | Path


def format_ass_timestamp(milliseconds: int) -> str:
    """Format milliseconds as ASS ``H:MM:SS.cc`` time."""

    if milliseconds < 0:
        raise SubtitleGenerationFailed("ASS timestamps cannot be negative")
    centiseconds_total = (milliseconds + 5) // 10
    total_seconds, centiseconds = divmod(centiseconds_total, 100)
    hours, remainder = divmod(total_seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    return f"{hours}:{minutes:02d}:{seconds:02d}.{centiseconds:02d}"


def escape_ass_text(text: str) -> str:
    """Escape text so braces and line breaks cannot become ASS override tags."""

    escaped = text.replace("\\", "\\\\")
    escaped = escaped.replace("{", "\\{").replace("}", "\\}")
    return escaped.replace("\r\n", "\\N").replace("\r", "\\N").replace("\n", "\\N")


def generate_ass(
    transcript: Transcript,
    style: ASSStyle | str = "clean",
    *,
    play_res_x: int = 1920,
    play_res_y: int = 1080,
) -> str:
    """Render a transcript as a styled ASS subtitle script."""

    resolved_style = get_style_preset(style) if isinstance(style, str) else style
    if play_res_x <= 0 or play_res_y <= 0:
        raise SubtitleGenerationFailed("ASS play resolution must be greater than zero")

    lines = [
        "[Script Info]",
        "; Script generated by video-mcp",
        "ScriptType: v4.00+",
        f"PlayResX: {play_res_x}",
        f"PlayResY: {play_res_y}",
        "ScaledBorderAndShadow: yes",
        "WrapStyle: 2",
        "YCbCr Matrix: None",
        "",
        "[V4+ Styles]",
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
        "OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, "
        "ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, "
        "Alignment, MarginL, MarginR, MarginV, Encoding",
        resolved_style.as_ass_line(),
        "",
        "[Events]",
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    ]

    previous_end = 0
    for cue_number, segment in enumerate(transcript.segments, start=1):
        _validate_segment(segment, cue_number, previous_end)
        lines.append(
            "Dialogue: "
            + ",".join(
                (
                    "0",
                    format_ass_timestamp(segment.start_ms),
                    format_ass_timestamp(segment.end_ms),
                    resolved_style.name,
                    segment.speaker or "",
                    "0",
                    "0",
                    "0",
                    "",
                    escape_ass_text(segment.text.strip()),
                )
            )
        )
        previous_end = segment.end_ms
    return "\n".join(lines) + "\n"


def write_ass(
    transcript: Transcript,
    output_path: PathLike,
    *,
    style: ASSStyle | str = "clean",
    play_res_x: int = 1920,
    play_res_y: int = 1080,
    overwrite: bool = False,
) -> Path:
    """Write an ASS file without replacing existing output by default."""

    destination = Path(output_path).expanduser()
    if destination.exists() and not overwrite:
        raise SubtitleGenerationFailed(
            f"Output already exists: {destination}; pass overwrite=True to replace it"
        )
    content = generate_ass(
        transcript,
        style,
        play_res_x=play_res_x,
        play_res_y=play_res_y,
    )
    destination.parent.mkdir(parents=True, exist_ok=True)
    with destination.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)
    return destination.resolve()


def _validate_segment(segment: SubtitleSegment, cue_number: int, previous_end: int) -> None:
    if segment.start_ms < 0 or segment.end_ms < 0:
        raise SubtitleGenerationFailed(f"ASS dialogue {cue_number} has a negative timestamp")
    if segment.end_ms <= segment.start_ms:
        raise SubtitleGenerationFailed(f"ASS dialogue {cue_number} must end after it starts")
    if segment.start_ms < previous_end:
        raise SubtitleGenerationFailed(f"ASS dialogue {cue_number} overlaps the previous dialogue")
