"""Deterministic Kdenlive Gen 5 project generation."""

from __future__ import annotations

import math
import shutil
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from fractions import Fraction
from pathlib import Path
from typing import Protocol

from video_mcp.errors import InputFileNotFound, KdenliveProjectFailed
from video_mcp.models import MediaInfo

PathLike = str | Path

KDENLIVE_FORMAT_VERSION = "1.1"
KDENLIVE_XML_NAMESPACE = "http://www.kdenlive.org/project"


class ProjectAdapter(Protocol):
    """Application-facing boundary for editable project exporters."""

    def create_project(self, source: PathLike, media: MediaInfo) -> KdenliveProject: ...

    def add_video(self, project: KdenliveProject, source: PathLike, media: MediaInfo) -> None: ...

    def add_subtitles(self, project: KdenliveProject, subtitles: PathLike) -> None: ...

    def save(
        self,
        project: KdenliveProject,
        destination: PathLike,
        *,
        overwrite: bool = False,
    ) -> Path: ...


@dataclass(slots=True)
class KdenliveProject:
    """In-memory project state owned by ``KdenliveProjectAdapter``."""

    root: ET.Element
    duration_frames: int
    subtitle_source: Path | None = None
    subtitle_filter: ET.Element | None = None
    _video_added: bool = field(default=False, repr=False)


class KdenliveProjectAdapter:
    """Write a minimal Kdenlive generation 5 project.

    The adapter intentionally writes a small, inspectable MLT graph. It does
    not launch Kdenlive, invoke ``melt``, or manipulate the editor UI.
    """

    def create_project(self, source: PathLike, media: MediaInfo) -> KdenliveProject:
        source_path = _require_file(source, "Source video")
        profile = _profile_from_media(media)
        duration_frames = _duration_frames(media.duration_ms, profile[0], profile[1])
        duration_out = str(max(duration_frames - 1, 0))

        ET.register_namespace("kdenlive", KDENLIVE_XML_NAMESPACE)
        root = ET.Element(
            "mlt",
            {
                "LC_NUMERIC": "C",
                "version": "7.40.0",
                "root": _mlt_path(source_path.parent),
                "producer": "main_bin",
            },
        )
        ET.SubElement(
            root,
            "profile",
            {
                "frame_rate_num": str(profile[0]),
                "frame_rate_den": str(profile[1]),
                "width": str(profile[2]),
                "height": str(profile[3]),
                "progressive": "1",
                "sample_aspect_num": "1",
                "sample_aspect_den": "1",
                "display_aspect_num": str(profile[2]),
                "display_aspect_den": str(profile[3]),
                "colorspace": "709",
                "description": f"{profile[2]}x{profile[3]} at {profile[0]}/{profile[1]} fps",
            },
        )
        project = KdenliveProject(root=root, duration_frames=duration_frames)
        self.add_video(project, source_path, media)

        # The sequence tractor is the editable timeline. The last tractor is
        # the Kdenlive-required wrapper for the active sequence.
        track_tractor = root.find("tractor[@id='tractor0']")
        sequence_tractor = root.find("tractor[@id='tractor1']")
        main_bin = root.find("playlist[@id='main_bin']")
        main_tractor = root.find("tractor[@id='maintractor']")
        if any(
            element is None for element in (track_tractor, sequence_tractor, main_bin, main_tractor)
        ):
            raise KdenliveProjectFailed("Internal Kdenlive project graph is incomplete")

        _set_out(track_tractor, duration_out)
        _set_out(sequence_tractor, duration_out)
        _set_out(main_tractor, duration_out)
        _set_out(main_bin, duration_out)
        _add_property(sequence_tractor, "kdenlive:uuid", "video-mcp-sequence-0")
        _add_property(sequence_tractor, "kdenlive:sequenceproperties.activeTrack", "0")
        _add_property(sequence_tractor, "kdenlive:sequenceproperties.tracks", "1")
        _add_property(main_bin, "kdenlive:docproperties.version", KDENLIVE_FORMAT_VERSION)
        _add_property(main_bin, "kdenlive:documentnotes", "Generated by video-mcp")
        _add_property(main_tractor, "kdenlive:projectTractor", "1")

        return project

    def add_video(self, project: KdenliveProject, source: PathLike, media: MediaInfo) -> None:
        """Add one source video as the first timeline track."""

        source_path = _require_file(source, "Source video")
        if project._video_added:
            raise KdenliveProjectFailed("Only one video source is supported in the minimal writer")

        video = media.video
        if video is None:
            raise KdenliveProjectFailed("Kdenlive export requires video metadata")
        duration_out = str(max(project.duration_frames - 1, 0))

        root = project.root
        producer = ET.Element("producer", {"id": "producer0", "in": "0", "out": duration_out})
        _add_property(producer, "mlt_service", "avformat")
        _add_property(producer, "resource", _mlt_path(source_path))
        _add_property(producer, "kdenlive:clipname", source_path.name)
        _add_property(producer, "kdenlive:folderid", "-1")
        _add_property(producer, "kdenlive:producer_type", "4")
        _add_property(producer, "kdenlive:originalurl", _mlt_path(source_path))

        playlist = ET.Element("playlist", {"id": "playlist0", "in": "0", "out": duration_out})
        _add_property(playlist, "kdenlive:track_name", "Video")
        ET.SubElement(
            playlist,
            "entry",
            {"producer": "producer0", "in": "0", "out": duration_out},
        )

        track_tractor = ET.Element("tractor", {"id": "tractor0", "in": "0", "out": duration_out})
        _add_property(track_tractor, "kdenlive:track_name", "Video")
        ET.SubElement(track_tractor, "track", {"producer": "playlist0"})

        sequence_tractor = ET.Element("tractor", {"id": "tractor1", "in": "0", "out": duration_out})
        ET.SubElement(sequence_tractor, "track", {"producer": "tractor0"})

        main_bin = ET.Element("playlist", {"id": "main_bin", "in": "0", "out": duration_out})
        ET.SubElement(main_bin, "entry", {"producer": "producer0", "in": "0", "out": duration_out})
        ET.SubElement(main_bin, "entry", {"producer": "tractor1", "in": "0", "out": duration_out})

        main_tractor = ET.Element("tractor", {"id": "maintractor", "in": "0", "out": duration_out})
        ET.SubElement(
            main_tractor,
            "track",
            {"producer": "tractor1", "in": "0", "out": duration_out},
        )

        # Keep the MLT object order close to Kdenlive's documented layout:
        # producers, tracks, sequence, project bin, then active wrapper.
        root.append(producer)
        root.append(playlist)
        root.append(track_tractor)
        root.append(sequence_tractor)
        root.append(main_bin)
        root.append(main_tractor)
        project._video_added = True

    def add_subtitles(self, project: KdenliveProject, subtitles: PathLike) -> None:
        """Attach an SRT subtitle filter to the active sequence tractor."""

        subtitle_path = _require_file(subtitles, "Subtitle")
        if project.subtitle_source is not None:
            raise KdenliveProjectFailed(
                "Only one subtitle asset is supported in the minimal writer"
            )
        sequence_tractor = project.root.find("tractor[@id='tractor1']")
        if sequence_tractor is None:
            raise KdenliveProjectFailed("Cannot add subtitles before adding a video")

        subtitle_filter = ET.SubElement(sequence_tractor, "filter", {"id": "filter0"})
        _add_property(subtitle_filter, "mlt_service", "avfilter.subtitles")
        _add_property(subtitle_filter, "internal_added", "237")
        _add_property(subtitle_filter, "kdenlive:locked", "1")
        project.subtitle_source = subtitle_path
        project.subtitle_filter = subtitle_filter

    def save(
        self,
        project: KdenliveProject,
        destination: PathLike,
        *,
        overwrite: bool = False,
    ) -> Path:
        """Write the project and its sibling SRT asset to disk."""

        if not project._video_added:
            raise KdenliveProjectFailed("Cannot save a project without a video source")
        destination_path = Path(destination).expanduser()
        if destination_path.suffix.lower() != ".kdenlive":
            raise KdenliveProjectFailed("Kdenlive project output must use the .kdenlive extension")
        destination_path = destination_path.resolve()
        subtitle_destination = Path(f"{destination_path}.srt")
        if destination_path.exists() and not overwrite:
            raise KdenliveProjectFailed(
                f"Output already exists: {destination_path}; pass overwrite=True to replace it"
            )
        if subtitle_destination.exists() and not overwrite:
            raise KdenliveProjectFailed(
                f"Subtitle output already exists: {subtitle_destination}; "
                "pass overwrite=True to replace it"
            )
        destination_path.parent.mkdir(parents=True, exist_ok=True)

        if project.subtitle_source is not None:
            if project.subtitle_filter is None:
                raise KdenliveProjectFailed("Subtitle source was set without a subtitle filter")
            _set_property(
                project.subtitle_filter,
                "av.filename",
                _mlt_path(subtitle_destination),
            )
            try:
                shutil.copyfile(project.subtitle_source, subtitle_destination)
            except OSError as exc:
                raise KdenliveProjectFailed(
                    f"Could not copy subtitle asset to {subtitle_destination}: {exc}"
                ) from exc

        try:
            ET.indent(project.root, space="  ")
            ET.ElementTree(project.root).write(
                destination_path,
                encoding="utf-8",
                xml_declaration=True,
                short_empty_elements=True,
            )
        except OSError as exc:
            raise KdenliveProjectFailed(
                f"Could not write Kdenlive project {destination_path}: {exc}"
            ) from exc
        return destination_path


def _require_file(path: PathLike, label: str) -> Path:
    resolved = Path(path).expanduser().resolve()
    if not resolved.is_file():
        raise InputFileNotFound(f"{label} file does not exist: {resolved}")
    return resolved


def _profile_from_media(media: MediaInfo) -> tuple[int, int, int, int]:
    video = media.video
    if video is None or video.width is None or video.height is None:
        raise KdenliveProjectFailed("Kdenlive export requires video dimensions")
    if video.width <= 0 or video.height <= 0:
        raise KdenliveProjectFailed("Kdenlive export requires positive video dimensions")
    if video.frame_rate is None or video.frame_rate <= 0:
        raise KdenliveProjectFailed("Kdenlive export requires a positive video frame rate")
    frame_rate = _frame_rate_rational(video.frame_rate)
    return frame_rate.numerator, frame_rate.denominator, video.width, video.height


def _frame_rate_rational(frame_rate: float) -> Fraction:
    """Preserve common broadcast rates such as 29.97 as 30000/1001."""

    common_rates = (
        (24000, 1001),
        (30000, 1001),
        (60000, 1001),
        (120000, 1001),
    )
    for numerator, denominator in common_rates:
        if abs(frame_rate - numerator / denominator) <= 0.005:
            return Fraction(numerator, denominator)
    return Fraction(frame_rate).limit_denominator(1001)


def _duration_frames(duration_ms: int | None, frame_rate_num: int, frame_rate_den: int) -> int:
    if duration_ms is None or duration_ms < 0:
        raise KdenliveProjectFailed("Kdenlive export requires a non-negative media duration")
    frames = math.ceil(duration_ms * frame_rate_num / (1000 * frame_rate_den))
    return max(frames, 1)


def _mlt_path(path: Path) -> str:
    """Use forward slashes so Windows paths remain portable XML values."""

    return path.resolve().as_posix()


def _add_property(parent: ET.Element, name: str, value: str) -> ET.Element:
    property_element = ET.SubElement(parent, "property", {"name": name})
    property_element.text = value
    return property_element


def _set_property(parent: ET.Element, name: str, value: str) -> ET.Element:
    matches = [child for child in parent.findall("property") if child.attrib.get("name") == name]
    if matches:
        property_element = matches[0]
        property_element.text = value
        for duplicate in matches[1:]:
            parent.remove(duplicate)
        return property_element
    return _add_property(parent, name, value)


def _set_out(element: ET.Element, value: str) -> None:
    element.set("out", value)
